### ISSUE TITLE
Illegal char code U+FFFE

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hxdoc#7]
```
panic: XML syntax error on line 78916: illegal character code U+FFFE

goroutine 1 [running]:
main.main.func1({{0xc0002dda00, 0x38}, {0xc0002dd9c0, 0x33}, {0xc0002936f0, 0xd}, 0xc0002a56b0, {{0xc0002a17a0, 0x2b}, 0x1, ...}})
	/home/runner/go/pkg/mod/github.com/go2hx/go2hxdoc@v0.0.0-20221018135452-aaaf729bb544/go2hxdoc.go:109 +0xa4c
main.main()
	/home/runner/go/pkg/mod/github.com/go2hx/go2hxdoc@v0.0.0-20221018135452-aaaf729bb544/go2hxdoc.go:158 +0x635
Error: Process completed with exit code 2.
```
https://github.com/go2hx/go2hx/actions/runs/3680940968/jobs/6227078190

**Comment by elliott5** [comment]
Looks like I need to sanitize the XML output from the Haxe compiler to remove any illegal characters before Go parses it.

**Comment by elliott5** [comment]
Test code:
```go
package main

import (
	"fmt"
	"unicode"
	"unicode/utf8"
)

func main() {
	fmt.Println(string(utf8.RuneError), string('\uFFFE'))
	fmt.Println(unicode.IsGraphic(utf8.RuneError), unicode.IsGraphic('\uFFFE'), utf8.ValidString(string('\uFFFE')))
}
```
Output:
```
� ￾
true false true
```

Plan: transform input, changing `!unicode.IsGraphic(testRune)` to `utf8.RuneError`.
... which is what github does in displaying this comment - so that the two characters output above appear to be the same!

**Comment by PXshadow** [comment]
Well done on the fix!
